### PR TITLE
fix a few typos and links

### PR DESCRIPTION
**Pull request by chadwhitacre**

### CODE REVIEW

**Comment by chadwhitacre** [comment]
Commits squashed per @orlando at https://github.com/vigetlabs/gulp-rails-pipeline/issues/6#issuecomment-160674678. Previous head was 630c01d8e073091f693bcde34579e68dde6391b9 ([commits](https://github.com/vigetlabs/gulp-rails-pipeline/commits/630c01d8e073091f693bcde34579e68dde6391b9/)).

**Comment by chadwhitacre** [comment]
Ready for review! :-)

cc: @greypants

**Comment by greypants** [comment]
:+1: Thanks dude!

**Comment by chadwhitacre** [comment]
:dancer:

**Pull request merged**
